name: Test
run-name: ${{github.actor}} trigger tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GO_VERSION: 1.26.1

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
      - name: Test
        run: go test ./... --cover --race --leak
